/**
 * Representations of pressable keys that aren't text
 */
export enum Keys {
  NULL = 'NULL',
  CANCEL = 'CANCEL',
  HELP = 'HELP',
  BACK_SPACE = 'BACK_SPACE',
  TAB = 'TAB',
  CLEAR = 'CLEAR',
  RETURN = 'RETURN',
  ENTER = 'ENTER',
  SHIFT = 'SHIFT',
  CONTROL = 'CONTROL',
  ALT = 'ALT',
  PAUSE = 'PAUSE',
  ESCAPE = 'ESCAPE',
  SPACE = 'SPACE',
  PAGE_UP = 'PAGE_UP',
  PAGE_DOWN = 'PAGE_DOWN',
  END = 'END',
  HOME = 'HOME',
  ARROW_LEFT = 'ARROW_LEFT',
  LEFT = 'LEFT',
  ARROW_UP = 'ARROW_UP',
  UP = 'UP',
  ARROW_RIGHT = 'ARROW_RIGHT',
  RIGHT = 'RIGHT',
  ARROW_DOWN = 'ARROW_DOWN',
  DOWN = 'DOWN',
  INSERT = 'INSERT',
  DELETE = 'DELETE',
  SEMICOLON = 'SEMICOLON',
  EQUALS = 'EQUALS',
  NUMPAD0 = 'NUMPAD0',
  NUMPAD1 = 'NUMPAD1',
  NUMPAD2 = 'NUMPAD2',
  NUMPAD3 = 'NUMPAD3',
  NUMPAD4 = 'NUMPAD4',
  NUMPAD5 = 'NUMPAD5',
  NUMPAD6 = 'NUMPAD6',
  NUMPAD7 = 'NUMPAD7',
  NUMPAD8 = 'NUMPAD8',
  NUMPAD9 = 'NUMPAD9',
  MULTIPLY = 'MULTIPLY',
  ADD = 'ADD',
  SEPARATOR = 'SEPARATOR',
  SUBTRACT = 'SUBTRACT',
  DECIMAL = 'DECIMAL',
  DIVIDE = 'DIVIDE',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  COMMAND = 'COMMAND',
  META = 'META',
}

// export enum Keys {
//     NULL = Key.NULL,
//     CANCEL = Key.CANCEL,
//     HELP = Key.HELP,
//     BACK_SPACE = Key.BACK_SPACE,
//     TAB = Key.TAB,
//     CLEAR = Key.CLEAR,
//     RETURN = Key.RETURN,
//     ENTER = Key.ENTER,
//     SHIFT = Key.SHIFT,
//     CONTROL = Key.CONTROL,
//     ALT = Key.ALT,
//     PAUSE = Key.PAUSE,
//     ESCAPE = Key.ESCAPE,
//     SPACE = Key.SPACE,
//     PAGE_UP = Key.PAGE_UP,
//     PAGE_DOWN = Key.PAGE_DOWN,
//     END = Key.END,
//     HOME = Key.HOME,
//     ARROW_LEFT = Key.ARROW_LEFT,
//     LEFT = Key.LEFT,
//     ARROW_UP = Key.ARROW_UP,
//     UP = Key.UP,
//     ARROW_RIGHT = Key.ARROW_RIGHT,
//     RIGHT = Key.RIGHT,
//     ARROW_DOWN = Key.ARROW_DOWN,
//     DOWN = Key.DOWN,
//     INSERT = Key.INSERT,
//     DELETE = Key.DELETE,
//     SEMICOLON = Key.SEMICOLON,
//     EQUALS = Key.EQUALS,
//     NUMPAD0 = Key.NUMPAD0,
//     NUMPAD1 = Key.NUMPAD1,
//     NUMPAD2 = Key.NUMPAD2,
//     NUMPAD3 = Key.NUMPAD3,
//     NUMPAD4 = Key.NUMPAD4,
//     NUMPAD5 = Key.NUMPAD5,
//     NUMPAD6 = Key.NUMPAD6,
//     NUMPAD7 = Key.NUMPAD7,
//     NUMPAD8 = Key.NUMPAD8,
//     NUMPAD9 = Key.NUMPAD9,
//     MULTIPLY = Key.MULTIPLY,
//     ADD = Key.ADD,
//     SEPARATOR = Key.SEPARATOR,
//     SUBTRACT = Key.SUBTRACT,
//     DECIMAL = Key.DECIMAL,
//     DIVIDE = Key.DIVIDE,
//     F1 = Key.F1,
//     F2 = Key.F2,
//     F3 = Key.F3,
//     F4 = Key.F4,
//     F5 = Key.F5,
//     F6 = Key.F6,
//     F7 = Key.F7,
//     F8 = Key.F8,
//     F9 = Key.F9,
//     F10 = Key.F10,
//     F11 = Key.F11,
//     F12 = Key.F12,
//     COMMAND = Key.COMMAND,
//     META = Key.META,
// }

/** Describes buttons available for the mouse */
export enum MouseButton {
  /** Left button */
  Left = 'left',

  /** Right button */
  Right = 'right',

  /** Middle (wheel) button */
  Middle = 'middle',
}
