logger:
  level: Warning
  Console:
    level: Info
owofify:
  level: uvu
extensions:
  Owofify Logger:
    enabled: false
    priority: 15
    version: ^1.0.0
  Indent Logger:
    enabled: true
  Go Back action:
    enabled: true
